# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-16 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u6821\u533a')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u8be6\u7ec6\u5730\u5740')),
            ],
        ),
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('LinuxL', 'Linux\u4e2d\u9ad8\u7ea7'), ('PythonFullStack', 'Python\u9ad8\u7ea7\u5168\u6808\u5f00\u53d1')], max_length=64, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('semester', models.IntegerField(verbose_name='\u5b66\u671f')),
                ('price', models.IntegerField(default=10000, verbose_name='\u5b66\u8d39')),
                ('memo', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8bf4\u660e')),
                ('start_date', models.DateField(verbose_name='\u5f00\u73ed\u65e5\u671f')),
                ('graduate_date', models.DateField(blank=True, null=True, verbose_name='\u7ed3\u4e1a\u65e5\u671f')),
                ('class_type', models.CharField(blank=True, choices=[('fulltime', '\u8131\u4ea7\u73ed'), ('online', '\u7f51\u7edc\u73ed'), ('weekend', '\u5468\u672b\u73ed')], max_length=64, null=True, verbose_name='\u73ed\u989d\u53ca\u7c7b\u578b')),
                ('campuses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Campuses', verbose_name='\u6821\u533a')),
                ('teachers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u8001\u5e08')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(help_text='QQ\u53f7\u5fc5\u987b\u552f\u4e00', max_length=64, unique=True, verbose_name='QQ')),
                ('qq_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ\u6635\u79f0')),
                ('name', models.CharField(blank=True, help_text='\u5b66\u5458\u62a5\u540d\u540e\uff0c\u8bf7\u6539\u4e3a\u771f\u5b9e\u59d3\u540d', max_length=32, null=True, verbose_name='\u59d3\u540d')),
                ('sex', models.CharField(blank=True, choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=16, null=True, verbose_name='\u6027\u522b')),
                ('birthday', models.DateField(blank=True, default=None, help_text='\u683c\u5f0fyyyy-mm-dd', null=True, verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('source', models.CharField(choices=[('qq', 'qq\u7fa4'), ('referral', '\u5185\u90e8\u8f6c\u4ecb\u7ecd'), ('website', '\u5b98\u65b9\u7f51\u7ad9'), ('baidu_ads', '\u767e\u5ea6\u63a8\u5e7f'), ('office_direct', '\u76f4\u63a5\u4e0a\u95e8'), ('WoM', '\u53e3\u7891'), ('public_class', '\u516c\u5f00\u8bfe'), ('website_luffy', '\u8def\u98de\u5b98\u7f51'), ('others', '\u5176\u5b83')], default='qq', max_length=64, verbose_name='\u5ba2\u6237\u6765\u6e90')),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('LinuxL', 'Linux\u4e2d\u9ad8\u7ea7'), ('PythonFullStack', 'Python\u9ad8\u7ea7\u5168\u6808\u5f00\u53d1')], max_length=22, verbose_name='\u54a8\u8be2\u8bfe\u7a0b')),
                ('class_type', models.CharField(choices=[('fulltime', '\u8131\u4ea7\u73ed'), ('online', '\u7f51\u7edc\u73ed'), ('weekend', '\u5468\u672b\u73ed')], default='fulltime', max_length=64, verbose_name='\u73ed\u7ea7\u7c7b\u578b')),
                ('customer_note', models.TextField(blank=True, null=True, verbose_name='\u5ba2\u6237\u5907\u6ce8')),
                ('status', models.CharField(choices=[('signed', '\u5df2\u62a5\u540d'), ('unregistered', '\u672a\u62a5\u540d'), ('studying', '\u5b66\u4e60\u4e2d'), ('paid_in_full', '\u5b66\u8d39\u5df2\u4ea4\u9f50')], default='unregistered', help_text='\u9009\u62e9\u5ba2\u6237\u6b64\u65f6\u7684\u72b6\u6001', max_length=64, verbose_name='\u72b6\u6001')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u54a8\u8be2\u65e5\u671f')),
                ('last_consult_date', models.DateField(auto_now_add=True, verbose_name='\u6700\u540e\u8ddf\u8fdb\u65e5\u671f')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='\u9884\u8ba1\u518d\u6b21\u8ddf\u8fdb\u65f6\u95f4')),
                ('class_list', models.ManyToManyField(to='app01.ClassList', verbose_name='\u5df2\u62a5\u73ed\u7ea7')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='\u9500\u552e')),
                ('introduce_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Customer', verbose_name='\u8f6c\u4ecb\u7ecd\u81ea\u5b66\u5458')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='classlist',
            unique_together=set([('course', 'semester', 'campuses')]),
        ),
    ]
