# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-17 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191216_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='\u8ddf\u8fdb\u5185\u5bb9...')),
                ('status', models.CharField(choices=[('A', '\u8fd1\u671f\u65e0\u62a5\u540d\u8ba1\u5212'), ('B', '1\u4e2a\u6708\u5185\u62a5\u540d'), ('C', '2\u5468\u5185\u62a5\u540d'), ('D', '1\u5468\u5185\u62a5\u540d'), ('E', '\u5b9a\u91d1'), ('F', '\u5230\u73ed'), ('G', '\u5168\u6b3e'), ('H', '\u65e0\u6548')], help_text='\u9009\u62e9\u5ba2\u6237\u6b64\u65f6\u7684\u72b6\u6001', max_length=8, verbose_name='\u8ddf\u8fdb\u72b6\u6001')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u8ddf\u8fdb\u65e5\u671f')),
                ('delete_status', models.BooleanField(default=False, verbose_name='\u5220\u9664\u72b6\u6001')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='\u8ddf\u8fdb\u4eba')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Customer', verbose_name='\u6240\u54a8\u8be2\u5ba2\u6237')),
            ],
        ),
    ]
