# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-18 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_consultrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_us', models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='\u4e3a\u4ec0\u4e48\u62a5\u540d')),
                ('your_expectation', models.TextField(blank=True, max_length=1024, null=True, verbose_name='\u5b66\u5b8c\u60f3\u8fbe\u5230\u7684\u5177\u4f53\u671f\u671b')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True, verbose_name='\u62a5\u540d\u65e5\u671f')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('delete_status', models.BooleanField(default=False, verbose_name='\u5220\u9664\u72b6\u6001')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Customer', verbose_name='\u5ba2\u6237\u540d\u79f0')),
                ('enrolment_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='\u6240\u62a5\u73ed\u7ea7')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Campuses')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('deposit', '\u8ba2\u91d1/\u62a5\u540d\u8d39'), ('tuition', '\u5b66\u8d39'), ('transfer', '\u8f6c\u73ed'), ('dropout', '\u9000\u5b66'), ('refund', '\u9000\u6b3e')], default='deposit', max_length=64, verbose_name='\u8d39\u7528\u7c7b\u578b')),
                ('paid_fee', models.IntegerField(default=0, verbose_name='\u8d39\u7528\u6570\u989d')),
                ('note', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u4ea4\u6b3e\u65e5\u671f')),
                ('course', models.CharField(blank=True, choices=[('LinuxL', 'Linux\u4e2d\u9ad8\u7ea7'), ('PythonFullStack', 'Python\u9ad8\u7ea7\u5168\u6808\u5f00\u53d1')], default='N/A', max_length=64, null=True, verbose_name='\u8bfe\u7a0b\u540d')),
                ('class_type', models.CharField(blank=True, choices=[('fulltime', '\u8131\u4ea7\u73ed'), ('online', '\u7f51\u7edc\u73ed'), ('weekend', '\u5468\u672b\u73ed')], default='N/A', max_length=64, null=True, verbose_name='\u73ed\u7ea7\u7c7b\u578b')),
                ('delete_status', models.BooleanField(default=False, verbose_name='\u5220\u9664\u72b6\u6001')),
                ('status', models.IntegerField(choices=[(1, '\u672a\u5ba1\u6838'), (2, '\u5df2\u5ba1\u6838')], default=1, verbose_name='\u5ba1\u6838')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='\u786e\u8ba4\u65e5\u671f')),
                ('confirm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirms', to=settings.AUTH_USER_MODEL, verbose_name='\u786e\u8ba4\u4eba')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u9500\u552e')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Customer', verbose_name='\u5ba2\u6237')),
                ('enrolment_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='\u6240\u62a5\u73ed\u7ea7')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([('enrolment_class', 'customer')]),
        ),
    ]
